In [12]:
#reference:http://cs231n.github.io/python-numpy-tutorial/

import numpy as np

test = np.array([1, 2, 3])  
print (type(test))            
#print test.shape            
#print test[0], test[1],test[2]  
#test[0] = 5                
#print test                 


<type 'numpy.ndarray'>


In [13]:

test2 = np.array([[1,2,3],[4,5,6]])   
print (test2.shape)                     
#print test2[0, 0]
#print test2

(2, 3)


In [15]:
#built in functions to create arrays:
#test = np.zeros((2,2))
#test = np.ones((1,2)) 
#test = np.random.random((2,2))
print (test)

[1 2 3]


In [18]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])


row_r1 = a[1, :]     
row_r2 = a[1:2, :]  

#print row_r1, row_r1.shape  
#print row_r2, row_r2.shape

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
#print col_r1, col_r1.shape
#print col_r2, col_r2.shape 

In [19]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
#print a[[0, 1, 2], [0, 1, 0]]  

# The above example of integer array indexing is equivalent to this:
#print np.array([a[0, 0], a[1, 1], a[2, 0]])  

In [20]:
#Elementwise Operations

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)


#print x + y
#print np.add(x, y)

#print x - y
#print np.subtract(x, y)

#print x * y
#print np.multiply(x, y)

#print x / y
#print np.divide(x, y)

#print np.sqrt(x)

In [21]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
#print v.dot(w)
#print np.dot(v, w)

# Matrix / vector product; both produce the rank 1 array [29 67]
#print x.dot(v)
#print np.dot(x, v)

# Matrix / matrix product;
#print x.dot(y)
#print np.dot(x, y)

In [22]:
x = np.array([[1,2],[3,4]])

#print np.sum(x)  # Compute sum of all elements;
#print np.sum(x, axis=0)  # Compute sum of each column;
#print np.sum(x, axis=1)  # Compute sum of each row; 

10
[4 6]
[3 7]
